# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-20 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors_app', '0002_auto_20170720_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
    ]
