# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-21 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors_app', '0004_auto_20170720_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='authors',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
    ]
