# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-21 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors_app', '0005_auto_20170721_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='books',
            field=models.ManyToManyField(related_name='author', to='book_authors_app.Book'),
        ),
    ]
