# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-20 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=28),
            preserve_default=False,
        ),
    ]
