# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-20 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login_app', '0002_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=254),
        ),
    ]
