# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-24 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_app', '0003_auto_20170724_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.CharField(max_length=254),
        ),
    ]
